### PR TITLE
[CJP-4784] Productize CJE DockerHub homepage

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
@reviewbybees /cc @carlossg @ndeloof @michaelneale

### CODE REVIEW

**Comment by ndeloof** [comment]
I'd prefer we don't duplicate documentation available for jenkins image, but link to it (I don't think we can include it) and focus on CloudBees specific details, like license management.

**Comment by cyrille-leclerc** [comment]
@ndeloof thanks!

> I'd prefer we don't duplicate documentation available for jenkins image

Can you elaborate more on your reasoning please? Afraid of duplication that would not be maintained? Something else?

> but link to it (I don't think we can include it) 

For the parts shared with OSS, what do you think of keeping the title on our CloudBees page (e.g. "Backing up data", "Passing JVM parameters", "Configuring logging"...) and having one link per chapter?

I would like to have these keywords on our page ("logging", "jvm parameters", "backup"...)

> and focus on CloudBees specific details, like license management.

+1, I plan to iterate on this (licensing, ops-center connectivity, terms of support...)

**Comment by ndeloof** [comment]
I'd like jenkins official image to be the reference for what is jenkins specific. 
Duplication is indeed source for sync issue and maintenance effort.
Typically, we won't duplicate here infos about the upstream Java image or System image, right ?

Would be ok to only repeat main chapter with link to the upstream doc, and maybe some specific notes on CloudBees solution (typically, backup, and CloudBees specific system parameters)

**Comment by cyrille-leclerc** [comment]
@ndeloof I'm happy with the solution you proposed.

**Comment by cyrille-leclerc** [comment]
@ndeloof hmm, there is not anchor in https://hub.docker.com/_/jenkins/ . I cannot create link to paragraphs :-(

**Comment by carlossg** [comment]
LGTM, do we need the same for the cjoc branch?

**Comment by ydubreuil** [comment]
LGTM

**Comment by cyrille-leclerc** [comment]
@carlossg yes, I'll do for CJOC a v1.0 that will have the same structure but we should soon adapt the content with ops center specific content

**Pull request merged**
